#ifndef KEYMAPPING_HPP
#define KEYMAPPING_HPP

#include <Arduino.h>  // Arduino IDEで使用するためのヘッダーを含む

// キーの修飾キーを定義
enum ModifierKey {
  MODIFIER_NONE = 0,
  MODIFIER_CTRL = KEYBOARD_MODIFIER_LEFTCTRL,
  MODIFIER_SHIFT = KEYBOARD_MODIFIER_LEFTSHIFT,
  MODIFIER_ALT = KEYBOARD_MODIFIER_LEFTALT,
  MODIFIER_GUI = KEYBOARD_MODIFIER_LEFTGUI,
  /*
  * KEYBOARD_MODIFIER_RIGHTCTRL
  * KEYBOARD_MODIFIER_RIGHTSHIFT
  * KEYBOARD_MODIFIER_RIGHTALT
  * KEYBOARD_MODIFIER_RIGHTGUI 
  */
};

struct KeyMapping {
  const char* keyString;
  uint8_t hidKey;
  uint8_t modifier;
};

// キーマッピングテーブル
static const KeyMapping keyMappings[] = {
  { "a", HID_KEY_A, 0 },
  { "b", HID_KEY_B, 0 },
  { "c", HID_KEY_C, 0 },
  { "d", HID_KEY_D, 0 },
  { "e", HID_KEY_E, 0 },
  { "f", HID_KEY_F, 0 },
  { "g", HID_KEY_G, 0 },
  { "h", HID_KEY_H, 0 },
  { "i", HID_KEY_I, 0 },
  { "j", HID_KEY_J, 0 },
  { "k", HID_KEY_K, 0 },
  { "l", HID_KEY_L, 0 },
  { "m", HID_KEY_M, 0 },
  { "n", HID_KEY_N, 0 },
  { "o", HID_KEY_O, 0 },
  { "p", HID_KEY_P, 0 },
  { "q", HID_KEY_Q, 0 },
  { "r", HID_KEY_R, 0 },
  { "s", HID_KEY_S, 0 },
  { "t", HID_KEY_T, 0 },
  { "u", HID_KEY_U, 0 },
  { "v", HID_KEY_V, 0 },
  { "w", HID_KEY_W, 0 },
  { "x", HID_KEY_X, 0 },
  { "y", HID_KEY_Y, 0 },
  { "z", HID_KEY_Z, 0 },

  { "A", HID_KEY_A, MODIFIER_SHIFT },
  { "B", HID_KEY_B, MODIFIER_SHIFT },
  { "C", HID_KEY_C, MODIFIER_SHIFT },
  { "D", HID_KEY_D, MODIFIER_SHIFT },
  { "E", HID_KEY_E, MODIFIER_SHIFT },
  { "F", HID_KEY_F, MODIFIER_SHIFT },
  { "G", HID_KEY_G, MODIFIER_SHIFT },
  { "H", HID_KEY_H, MODIFIER_SHIFT },
  { "I", HID_KEY_I, MODIFIER_SHIFT },
  { "J", HID_KEY_J, MODIFIER_SHIFT },
  { "K", HID_KEY_K, MODIFIER_SHIFT },
  { "L", HID_KEY_L, MODIFIER_SHIFT },
  { "M", HID_KEY_M, MODIFIER_SHIFT },
  { "N", HID_KEY_N, MODIFIER_SHIFT },
  { "O", HID_KEY_O, MODIFIER_SHIFT },
  { "P", HID_KEY_P, MODIFIER_SHIFT },
  { "Q", HID_KEY_Q, MODIFIER_SHIFT },
  { "R", HID_KEY_R, MODIFIER_SHIFT },
  { "S", HID_KEY_S, MODIFIER_SHIFT },
  { "T", HID_KEY_T, MODIFIER_SHIFT },
  { "U", HID_KEY_U, MODIFIER_SHIFT },
  { "V", HID_KEY_V, MODIFIER_SHIFT },
  { "W", HID_KEY_W, MODIFIER_SHIFT },
  { "X", HID_KEY_X, MODIFIER_SHIFT },
  { "Y", HID_KEY_Y, MODIFIER_SHIFT },
  { "Z", HID_KEY_Z, MODIFIER_SHIFT },

  { "1", HID_KEY_1, 0 },
  { "2", HID_KEY_2, 0 },
  { "3", HID_KEY_3, 0 },
  { "4", HID_KEY_4, 0 },
  { "5", HID_KEY_5, 0 },
  { "6", HID_KEY_6, 0 },
  { "7", HID_KEY_7, 0 },
  { "8", HID_KEY_8, 0 },
  { "9", HID_KEY_9, 0 },
  { "0", HID_KEY_0, 0 },
  { "-", HID_KEY_MINUS, 0 },
  { "^", HID_KEY_EQUAL, 0 },
  { "\\", HID_KEY_KANJI3, 0 },

  { "!", HID_KEY_1, MODIFIER_SHIFT },
  { "\"", HID_KEY_2, MODIFIER_SHIFT },
  { "#", HID_KEY_3, MODIFIER_SHIFT },
  { "$", HID_KEY_4, MODIFIER_SHIFT },
  { "%", HID_KEY_5, MODIFIER_SHIFT },
  { "&", HID_KEY_6, MODIFIER_SHIFT },
  { "'", HID_KEY_7, MODIFIER_SHIFT },
  { "(", HID_KEY_8, MODIFIER_SHIFT },
  { ")", HID_KEY_9, MODIFIER_SHIFT },
  { "=", HID_KEY_MINUS, MODIFIER_SHIFT },
  { "~", HID_KEY_EQUAL, MODIFIER_SHIFT },
  { "|", HID_KEY_KANJI3, MODIFIER_SHIFT },

  { "@", HID_KEY_BRACKET_LEFT, 0 },
  { "[", HID_KEY_BRACKET_RIGHT, 0 },
  { "`", HID_KEY_BRACKET_LEFT, MODIFIER_SHIFT },
  { "{", HID_KEY_BRACKET_RIGHT, MODIFIER_SHIFT },

  { ";", HID_KEY_SEMICOLON, 0 },
  { ":", HID_KEY_APOSTROPHE, 0 },
  { "]", HID_KEY_EUROPE_1, 0 },
  { "+", HID_KEY_SEMICOLON, MODIFIER_SHIFT },
  { "*", HID_KEY_APOSTROPHE, MODIFIER_SHIFT },
  { "}", HID_KEY_EUROPE_1, MODIFIER_SHIFT },

  { ",", HID_KEY_COMMA, 0 },
  { ".", HID_KEY_PERIOD, 0 },
  { "/", HID_KEY_SLASH, 0 },
  { "<", HID_KEY_COMMA, MODIFIER_SHIFT },
  { ">", HID_KEY_PERIOD, MODIFIER_SHIFT },
  { "?", HID_KEY_SLASH, MODIFIER_SHIFT },
  { "_", HID_KEY_KANJI1, MODIFIER_SHIFT },

  { "Process", HID_KEY_GRAVE, 0 },
  { "Backspace", HID_KEY_BACKSPACE, 0 },
  { "tab", HID_KEY_TAB, 0 },
  { "capslock", HID_KEY_CAPS_LOCK, 0 },
  { "enter", HID_KEY_ENTER, 0 },
  { "space", HID_KEY_SPACE, 0 },
  { "insert", HID_KEY_INSERT, 0 },
  { "delete", HID_KEY_DELETE, 0 },
  { "arrowleft", HID_KEY_ARROW_LEFT, 0 },
  { "arrowright", HID_KEY_ARROW_RIGHT, 0 },
  { "arrowup", HID_KEY_ARROW_UP, 0 },
  { "arrowdown", HID_KEY_ARROW_DOWN, 0 },
  { "home", HID_KEY_HOME, 0 },
  { "end", HID_KEY_END, 0 },
  { "pageup", HID_KEY_PAGE_UP, 0 },
  { "pagedown", HID_KEY_PAGE_DOWN, 0 },
  { "numlock", HID_KEY_NUM_LOCK, 0 },
  { "Escape", HID_KEY_ESCAPE, 0 },
  { "Enter", HID_KEY_KEYPAD_ENTER, 0 },

  { "f1", HID_KEY_F1, 0 },
  { "f2", HID_KEY_F2, 0 },
  { "f3", HID_KEY_F3, 0 },
  { "f4", HID_KEY_F4, 0 },
  { "f5", HID_KEY_F5, 0 },
  { "f6", HID_KEY_F6, 0 },
  { "f7", HID_KEY_F7, 0 },
  { "f8", HID_KEY_F8, 0 },
  { "f9", HID_KEY_F9, 0 },
  { "f10", HID_KEY_F10, 0 },
  { "f11", HID_KEY_F11, 0 },
  { "f12", HID_KEY_F12, 0 },

  { "Control+a", HID_KEY_A, MODIFIER_CTRL },
  { "Control+b", HID_KEY_B, MODIFIER_CTRL },
  { "Control+c", HID_KEY_C, MODIFIER_CTRL },
  { "Control+d", HID_KEY_D, MODIFIER_CTRL },
  { "Control+e", HID_KEY_E, MODIFIER_CTRL },
  { "Control+f", HID_KEY_F, MODIFIER_CTRL },
  { "Control+g", HID_KEY_G, MODIFIER_CTRL },
  { "Control+h", HID_KEY_H, MODIFIER_CTRL },
  { "Control+i", HID_KEY_I, MODIFIER_CTRL },
  { "Control+j", HID_KEY_J, MODIFIER_CTRL },
  { "Control+k", HID_KEY_K, MODIFIER_CTRL },
  { "Control+l", HID_KEY_L, MODIFIER_CTRL },
  { "Control+m", HID_KEY_M, MODIFIER_CTRL },
  { "Control+n", HID_KEY_N, MODIFIER_CTRL },
  { "Control+o", HID_KEY_O, MODIFIER_CTRL },
  { "Control+p", HID_KEY_P, MODIFIER_CTRL },
  { "Control+q", HID_KEY_Q, MODIFIER_CTRL },
  { "Control+r", HID_KEY_R, MODIFIER_CTRL },
  { "Control+s", HID_KEY_S, MODIFIER_CTRL },
  { "Control+t", HID_KEY_T, MODIFIER_CTRL },
  { "Control+u", HID_KEY_U, MODIFIER_CTRL },
  { "Control+v", HID_KEY_V, MODIFIER_CTRL },
  { "Control+w", HID_KEY_W, MODIFIER_CTRL },
  { "Control+x", HID_KEY_X, MODIFIER_CTRL },
  { "Control+y", HID_KEY_Y, MODIFIER_CTRL },
  { "Control+z", HID_KEY_Z, MODIFIER_CTRL },

  { "Control+1", HID_KEY_1, MODIFIER_CTRL },
  { "Control+2", HID_KEY_2, MODIFIER_CTRL },
  { "Control+3", HID_KEY_3, MODIFIER_CTRL },
  { "Control+4", HID_KEY_4, MODIFIER_CTRL },
  { "Control+5", HID_KEY_5, MODIFIER_CTRL },
  { "Control+6", HID_KEY_6, MODIFIER_CTRL },
  { "Control+7", HID_KEY_7, MODIFIER_CTRL },
  { "Control+8", HID_KEY_8, MODIFIER_CTRL },
  { "Control+9", HID_KEY_9, MODIFIER_CTRL },
  { "Control+0", HID_KEY_0, MODIFIER_CTRL },
  { "Control+-", HID_KEY_MINUS, MODIFIER_CTRL },
  { "Control+^", HID_KEY_EQUAL, MODIFIER_CTRL },
  { "Control+\\", HID_KEY_BACKSLASH, MODIFIER_CTRL },

  { "Control+@", HID_KEY_BRACKET_LEFT, MODIFIER_CTRL },
  { "Control+[", HID_KEY_BRACKET_RIGHT, MODIFIER_CTRL },

  { "Control+;", HID_KEY_SEMICOLON, MODIFIER_CTRL },
  { "Control+:", HID_KEY_APOSTROPHE, MODIFIER_CTRL },
  { "Control+]", HID_KEY_EUROPE_1, MODIFIER_CTRL },

  { "Control+,", HID_KEY_COMMA, MODIFIER_CTRL },
  { "Control+.", HID_KEY_PERIOD, MODIFIER_CTRL },
  { "Control+/", HID_KEY_SLASH, MODIFIER_CTRL },

  { "Control+Process", HID_KEY_GRAVE, MODIFIER_CTRL },
  { "Control+backspace", HID_KEY_BACKSPACE, MODIFIER_CTRL },
  { "Control+tab", HID_KEY_TAB, MODIFIER_CTRL },
  { "Control+capslock", HID_KEY_CAPS_LOCK, MODIFIER_CTRL },
  { "Control+enter", HID_KEY_ENTER, MODIFIER_CTRL },
  { "Control+space", HID_KEY_SPACE, MODIFIER_CTRL },
  { "Control+insert", HID_KEY_INSERT, MODIFIER_CTRL },
  { "Control+delete", HID_KEY_DELETE, MODIFIER_CTRL },
  { "Control+arrowleft", HID_KEY_ARROW_LEFT, MODIFIER_CTRL },
  { "Control+arrowright", HID_KEY_ARROW_RIGHT, MODIFIER_CTRL },
  { "Control+arrowup", HID_KEY_ARROW_UP, MODIFIER_CTRL },
  { "Control+arrowdown", HID_KEY_ARROW_DOWN, MODIFIER_CTRL },
  { "Control+home", HID_KEY_HOME, MODIFIER_CTRL },
  { "Control+end", HID_KEY_END, MODIFIER_CTRL },
  { "Control+pageup", HID_KEY_PAGE_UP, MODIFIER_CTRL },
  { "Control+pagedown", HID_KEY_PAGE_DOWN, MODIFIER_CTRL },
  { "Control+numlock", HID_KEY_NUM_LOCK, MODIFIER_CTRL },
  { "Control+Escape", HID_KEY_ESCAPE, MODIFIER_CTRL },
  { "Control+Enter", HID_KEY_KEYPAD_ENTER, MODIFIER_CTRL },

  { "Control+f1", HID_KEY_F1, MODIFIER_CTRL },
  { "Control+f2", HID_KEY_F2, MODIFIER_CTRL },
  { "Control+f3", HID_KEY_F3, MODIFIER_CTRL },
  { "Control+f4", HID_KEY_F4, MODIFIER_CTRL },
  { "Control+f5", HID_KEY_F5, MODIFIER_CTRL },
  { "Control+f6", HID_KEY_F6, MODIFIER_CTRL },
  { "Control+f7", HID_KEY_F7, MODIFIER_CTRL },
  { "Control+f8", HID_KEY_F8, MODIFIER_CTRL },
  { "Control+f9", HID_KEY_F9, MODIFIER_CTRL },
  { "Control+f10", HID_KEY_F10, MODIFIER_CTRL },
  { "Control+f11", HID_KEY_F11, MODIFIER_CTRL },
  { "Control+f12", HID_KEY_F12, MODIFIER_CTRL },

  { "Shift+Process", HID_KEY_GRAVE, MODIFIER_SHIFT },
  { "Shift+backspace", HID_KEY_BACKSPACE, MODIFIER_SHIFT },
  { "Shift+tab", HID_KEY_TAB, MODIFIER_SHIFT },
  { "Shift+capslock", HID_KEY_CAPS_LOCK, MODIFIER_SHIFT },
  { "Shift+enter", HID_KEY_ENTER, MODIFIER_SHIFT },
  { "Shift+space", HID_KEY_SPACE, MODIFIER_SHIFT },
  { "Shift+insert", HID_KEY_INSERT, MODIFIER_SHIFT },
  { "Shift+delete", HID_KEY_DELETE, MODIFIER_SHIFT },
  { "Shift+arrowleft", HID_KEY_ARROW_LEFT, MODIFIER_SHIFT },
  { "Shift+arrowright", HID_KEY_ARROW_RIGHT, MODIFIER_SHIFT },
  { "Shift+arrowup", HID_KEY_ARROW_UP, MODIFIER_SHIFT },
  { "Shift+arrowdown", HID_KEY_ARROW_DOWN, MODIFIER_SHIFT },
  { "Shift+home", HID_KEY_HOME, MODIFIER_SHIFT },
  { "Shift+end", HID_KEY_END, MODIFIER_SHIFT },
  { "Shift+pageup", HID_KEY_PAGE_UP, MODIFIER_SHIFT },
  { "Shift+pagedown", HID_KEY_PAGE_DOWN, MODIFIER_SHIFT },
  { "Shift+numlock", HID_KEY_NUM_LOCK, MODIFIER_SHIFT },
  { "Shift+Escape", HID_KEY_ESCAPE, MODIFIER_SHIFT },
  { "Shift+Enter", HID_KEY_KEYPAD_ENTER, MODIFIER_SHIFT },

  { "Shift+f1", HID_KEY_F1, MODIFIER_SHIFT },
  { "Shift+f2", HID_KEY_F2, MODIFIER_SHIFT },
  { "Shift+f3", HID_KEY_F3, MODIFIER_SHIFT },
  { "Shift+f4", HID_KEY_F4, MODIFIER_SHIFT },
  { "Shift+f5", HID_KEY_F5, MODIFIER_SHIFT },
  { "Shift+f6", HID_KEY_F6, MODIFIER_SHIFT },
  { "Shift+f7", HID_KEY_F7, MODIFIER_SHIFT },
  { "Shift+f8", HID_KEY_F8, MODIFIER_SHIFT },
  { "Shift+f9", HID_KEY_F9, MODIFIER_SHIFT },
  { "Shift+f10", HID_KEY_F10, MODIFIER_SHIFT },
  { "Shift+f11", HID_KEY_F11, MODIFIER_SHIFT },
  { "Shift+f12", HID_KEY_F12, MODIFIER_SHIFT },


  { "Alt+a", HID_KEY_A, MODIFIER_ALT },
  { "Alt+b", HID_KEY_B, MODIFIER_ALT },
  { "Alt+c", HID_KEY_C, MODIFIER_ALT },
  { "Alt+d", HID_KEY_D, MODIFIER_ALT },
  { "Alt+e", HID_KEY_E, MODIFIER_ALT },
  { "Alt+f", HID_KEY_F, MODIFIER_ALT },
  { "Alt+g", HID_KEY_G, MODIFIER_ALT },
  { "Alt+h", HID_KEY_H, MODIFIER_ALT },
  { "Alt+i", HID_KEY_I, MODIFIER_ALT },
  { "Alt+j", HID_KEY_J, MODIFIER_ALT },
  { "Alt+k", HID_KEY_K, MODIFIER_ALT },
  { "Alt+l", HID_KEY_L, MODIFIER_ALT },
  { "Alt+m", HID_KEY_M, MODIFIER_ALT },
  { "Alt+n", HID_KEY_N, MODIFIER_ALT },
  { "Alt+o", HID_KEY_O, MODIFIER_ALT },
  { "Alt+p", HID_KEY_P, MODIFIER_ALT },
  { "Alt+q", HID_KEY_Q, MODIFIER_ALT },
  { "Alt+r", HID_KEY_R, MODIFIER_ALT },
  { "Alt+s", HID_KEY_S, MODIFIER_ALT },
  { "Alt+t", HID_KEY_T, MODIFIER_ALT },
  { "Alt+u", HID_KEY_U, MODIFIER_ALT },
  { "Alt+v", HID_KEY_V, MODIFIER_ALT },
  { "Alt+w", HID_KEY_W, MODIFIER_ALT },
  { "Alt+x", HID_KEY_X, MODIFIER_ALT },
  { "Alt+y", HID_KEY_Y, MODIFIER_ALT },
  { "Alt+z", HID_KEY_Z, MODIFIER_ALT },

  { "Alt+1", HID_KEY_1, MODIFIER_ALT },
  { "Alt+2", HID_KEY_2, MODIFIER_ALT },
  { "Alt+3", HID_KEY_3, MODIFIER_ALT },
  { "Alt+4", HID_KEY_4, MODIFIER_ALT },
  { "Alt+5", HID_KEY_5, MODIFIER_ALT },
  { "Alt+6", HID_KEY_6, MODIFIER_ALT },
  { "Alt+7", HID_KEY_7, MODIFIER_ALT },
  { "Alt+8", HID_KEY_8, MODIFIER_ALT },
  { "Alt+9", HID_KEY_9, MODIFIER_ALT },
  { "Alt+0", HID_KEY_0, MODIFIER_ALT },
  { "Alt+-", HID_KEY_MINUS, MODIFIER_ALT },
  { "Alt+^", HID_KEY_EQUAL, MODIFIER_ALT },
  { "Alt+\\", HID_KEY_BACKSLASH, MODIFIER_ALT },

  { "Alt+@", HID_KEY_BRACKET_LEFT, MODIFIER_ALT },
  { "Alt+[", HID_KEY_BRACKET_RIGHT, MODIFIER_ALT },

  { "Alt+;", HID_KEY_SEMICOLON, MODIFIER_ALT },
  { "Alt+:", HID_KEY_APOSTROPHE, MODIFIER_ALT },
  { "Alt+]", HID_KEY_EUROPE_1, MODIFIER_ALT },

  { "Alt+,", HID_KEY_COMMA, MODIFIER_ALT },
  { "Alt+.", HID_KEY_PERIOD, MODIFIER_ALT },
  { "Alt+/", HID_KEY_SLASH, MODIFIER_ALT },

  { "Alt+Process", HID_KEY_GRAVE, MODIFIER_ALT },
  { "Alt+backspace", HID_KEY_BACKSPACE, MODIFIER_ALT },
  { "Alt+tab", HID_KEY_TAB, MODIFIER_ALT },
  { "Alt+capslock", HID_KEY_CAPS_LOCK, MODIFIER_ALT },
  { "Alt+enter", HID_KEY_ENTER, MODIFIER_ALT },
  { "Alt+space", HID_KEY_SPACE, MODIFIER_ALT },
  { "Alt+insert", HID_KEY_INSERT, MODIFIER_ALT },
  { "Alt+delete", HID_KEY_DELETE, MODIFIER_ALT },
  { "Alt+arrowleft", HID_KEY_ARROW_LEFT, MODIFIER_ALT },
  { "Alt+arrowright", HID_KEY_ARROW_RIGHT, MODIFIER_ALT },
  { "Alt+arrowup", HID_KEY_ARROW_UP, MODIFIER_ALT },
  { "Alt+arrowdown", HID_KEY_ARROW_DOWN, MODIFIER_ALT },
  { "Alt+home", HID_KEY_HOME, MODIFIER_ALT },
  { "Alt+end", HID_KEY_END, MODIFIER_ALT },
  { "Alt+pageup", HID_KEY_PAGE_UP, MODIFIER_ALT },
  { "Alt+pagedown", HID_KEY_PAGE_DOWN, MODIFIER_ALT },
  { "Alt+numlock", HID_KEY_NUM_LOCK, MODIFIER_ALT },
  { "Alt+Escape", HID_KEY_ESCAPE, MODIFIER_ALT },
  { "Alt+Enter", HID_KEY_KEYPAD_ENTER, MODIFIER_ALT },

  { "Alt+f1", HID_KEY_F1, MODIFIER_ALT },
  { "Alt+f2", HID_KEY_F2, MODIFIER_ALT },
  { "Alt+f3", HID_KEY_F3, MODIFIER_ALT },
  { "Alt+f4", HID_KEY_F4, MODIFIER_ALT },
  { "Alt+f5", HID_KEY_F5, MODIFIER_ALT },
  { "Alt+f6", HID_KEY_F6, MODIFIER_ALT },
  { "Alt+f7", HID_KEY_F7, MODIFIER_ALT },
  { "Alt+f8", HID_KEY_F8, MODIFIER_ALT },
  { "Alt+f9", HID_KEY_F9, MODIFIER_ALT },
  { "Alt+f10", HID_KEY_F10, MODIFIER_ALT },
  { "Alt+f11", HID_KEY_F11, MODIFIER_ALT },
  { "Alt+f12", HID_KEY_F12, MODIFIER_ALT },
};
#endif  // KEYMAPPING_HPP